name: Tests and Linting

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Pre-requisites
        run: |
          cp .env.template .env
          mkdir secrets
          printf "123-bot-secret-456" > secrets/bot_api_key
      - name: Build and Run bot container
        run: docker-compose build --build-arg REQS_FILE=requirements-dev.txt
      - name: Linting
        run: docker-compose exec bot flake8 --max-line-length=120
      - name: Unit tests
        run: docker-compose exec bot pytest --cov=bot/
#      - name: Install dependencies
#        run: |
#          pip install -r requirements-dev.txt
#      - name: Linting
#        run: |
#          flake8 --max-line-length=120
#      - name: Test with pytest
#        run: |
#          pytest -x --cov=bot/

